- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)

# AUR apps
- include_tasks: aur.yml
  when: use_aur == True

# Basic apps
- include_tasks: core-apps.yml

# Dotfiles
- include_tasks: dotfiles.yml
  when: pull_dotfiles == True

# Web Browser
- include_tasks: firefox.yml
  when: install_firefox == True

# flatpak 
- include_tasks: flatpak.yml
  when: install_flatpak == True

# gaming
- include_tasks: gaming.yml
  when: install_gaming == True
# NVIDIA
- include_tasks: nvidia.yml
  when: install_nvidia == True

# Install and configure zsh
- include_tasks: zsh.yml
  when: setup_zsh == True

# yay apps
- include_tasks: yay.yml
  when: install_yay == True

# Work Stuff
- include_tasks: Work.yml
  when: install_work == True




