- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)

# AUR apps
- include_tasks: aur.yml
  when: use_aur == True

# Basic apps
- include_tasks: core-apps.yml

# Dotfiles
- include_tasks: dotfiles.yml
  when: pull_dotfiles == True

# Web Browser
- include_tasks: firefox.yml
  when: install_firefox == True

# gaming
- include_tasks: gaming.yml
  wheh: install_gaming == true
# NVIDIA
- include_tasks: nvidia.yml
  when: install_nvidia == true

# Install and configure zsh
- include_tasks: zsh.yml
  when: setup_zsh == True

# yay apps
- include_tasks: yay.yml
  when: install_yay_apps == True






